/*Create country table*/
CREATE TABLE IF NOT EXISTS country(
	countryId INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	country VARCHAR(50) NOT NULL,
	createDate DATETIME NOT NULL,
	createdBy VARCHAR(40) NOT NULL,
	lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdateBy VARCHAR(40) NOT NULL
);

/*Create city table*/
CREATE TABLE IF NOT EXISTS city(
	cityId INT(10) NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	city VARCHAR(50) NOT NULL,
	countryId INT(10) NOT NULL,
	createDate DATETIME NOT NULL,
	createdBy VARCHAR(40) NOT NULL,
	lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdateBy VARCHAR(40) NOT NULL,
	FOREIGN KEY(countryId) REFERENCES country(countryId) ON DELETE CASCADE ON UPDATE CASCADE
);

/*Create address table*/
CREATE TABLE IF NOT EXISTS address(
	addressId INT(10) NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	address VARCHAR(50) NOT NULL,
	address2 VARCHAR(50),
	cityId INT(10) NOT NULL,
	postalCode VARCHAR(10) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	createDate DATETIME NOT NULL,
	createdBy VARCHAR(40) NOT NULL,
	lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdateBy VARCHAR(40) NOT NULL,
	FOREIGN KEY(cityId) REFERENCES city(cityId) ON DELETE CASCADE ON UPDATE CASCADE
);

/*Create customer table*/
CREATE TABLE IF NOT EXISTS customer(
	customerId INT(10) NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	customerName VARCHAR(45) NOT NULL,
	addressId INT(10),
	active TINYINT(1) NOT NULL,
	createDate DATETIME NOT NULL,
	createdBy VARCHAR(40) NOT NULL,
	lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdateBy VARCHAR(40) NOT NULL,
	FOREIGN KEY(addressId) REFERENCES address(addressId) ON UPDATE CASCADE ON DELETE SET NULL
);

/*Create user table*/
CREATE TABLE IF NOT EXISTS user(
	userId INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	userName VARCHAR(50) NOT NULL,
	password VARCHAR(64) NOT NULL,
	active TINYINT(1) NOT NULL,
	createDate DATETIME NOT NULL,
	createdBy VARCHAR(40) NOT NULL,
	lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdateBy VARCHAR(40) NOT NULL
);

/*Create appointment table*/
CREATE TABLE IF NOT EXISTS appointment(
	appointmentId INT(10) NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	customerId INT(10) NOT NULL,
	userId INT NOT NULL,
	title VARCHAR(255),
	description TEXT,
	location TEXT,
	contact TEXT,
	type TEXT NOT NULL,
	url VARCHAR(255),
	start DATETIME NOT NULL,
	end DATETIME NOT NULL,
	createDate DATETIME NOT NULL,
	createdBy VARCHAR(40) NOT NULL,
	lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdateBy VARCHAR(40) NOT NULL,
	FOREIGN KEY(customerId) REFERENCES customer(customerId) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(userId) REFERENCES user(userId) ON DELETE CASCADE ON UPDATE CASCADE
);